import Head from "next/head";
import { useState } from "react";

function Home() {
  const [state, setState] = useState("");
  const [keyb, setKeyb] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
     
      </main>

      <footer></footer>
    </div>
  );
}


export default Home